---
- name: VScode and extensions
  hosts: localhost

  tasks:
    - name: Install core vscode packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - visual-studio-code

    - name: Install ansible-dev-tools using pipx
      ansible.builtin.pip:
        name: ansible-dev-tools
        executable: pipx
        state: present

    - name: Install Drupal supporting vscode extensions
      ansible.builtin.shell:
        cmd: code --install-extension "{{ item }}"
        executable: /bin/bash
      with_items:
        # General editor extensions
        - editorconfig.editorconfig
        - vscode.markdown-language-features
        - redhat.ansible
        - trunk.io
        - redhat.vscode-yaml
        - vscode-icons-team.vscode-icons
        - donjayamanne.githistory
        - streetsidesoftware.code-spell-checker
        # PHP extensions
        - vscode.php-language-features
        - valeryanm.vscode-phpsab
        - bmewburn.vscode-intelephense-client
        - devsense.phptools-vscode
        - sanderronde.phpstan-vscode
        - xdebug.php-debug
        - DEVSENSE.composer-php-vscode
        # Drupal extensions
        - marcostazi.vs-code-drupal
        - andrewdavidblum.drupal-smart-snippets
        - davis-are.drupal-sdc-helper
        # Drupal theming extensions
        - bradlc.vscode-tailwindcss
        - nadim-vscode.twig-code-snippets
        - mblode.twig-language-2
        # Workflow extensions
        - atlassian.atlascode
